# Generated by Django 4.1.3 on 2022-12-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0003_alter_likes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
