# Generated by Django 4.1.3 on 2022-12-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0004_likes_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='dislikes',
            field=models.IntegerField(),
        ),
    ]
